import { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowLeft, Calendar, Users, Target, Zap, CheckCircle2 } from 'lucide-react';
import { Card } from '../components/ui/Card';

const divisionsData = {
  iic: {
    name: 'Institution Innovation Council',
    shortName: 'IIC',
    color: 'from-blue-600 to-cyan-500',
    bgLight: 'bg-blue-500/10',
    textDark: 'text-blue-400',
    textPrimary: 'text-blue-400',
    description: 'IIC at PCCOE is established under the guidelines of MoE\'s Innovation Cell (MIC) to systematically foster the culture of innovation and startup ecosystem in education institutions.',
    objectives: [
      'To create a vibrant local innovation ecosystem.',
      'Start-up supporting mechanism in HEIs.',
      'Prepare institute for Atal Ranking of Institutions on Innovation Achievements Framework.',
      'Establish function ecosystem for scouting ideas and pre-incubation of ideas.',
    ],
    activities: [
      { title: 'Ideathon 2025', date: 'Oct 2025', desc: 'Annual idea pitching competition for first-year students.' },
      { title: 'Startup Bootcamp', date: 'Jan 2026', desc: 'Intensive 3-day workshop on building a startup from scratch.' },
      { title: 'Founder Talk Series', date: 'Monthly', desc: 'Interactive sessions with successful alumni entrepreneurs.' },
    ],
    image: 'https://picsum.photos/seed/iic/1200/600?blur=2'
  },
  ipr: {
    name: 'Intellectual Property Rights Cell',
    shortName: 'IPR',
    color: 'from-purple-600 to-pink-500',
    bgLight: 'bg-purple-500/10',
    textDark: 'text-purple-400',
    textPrimary: 'text-purple-400',
    description: 'The IPR Cell facilitates the protection of intellectual property generated by students and faculty, providing guidance on patent filing, copyrights, and trademarks.',
    objectives: [
      'To create awareness about IPR among faculty and students.',
      'To provide guidance and support for patent drafting and filing.',
      'To manage the intellectual property portfolio of the institute.',
      'To facilitate technology transfer and commercialization.',
    ],
    activities: [
      { title: 'Patent Drafting Workshop', date: 'Nov 2025', desc: 'Hands-on training on drafting patent claims.' },
      { title: 'Copyright Awareness Week', date: 'Feb 2026', desc: 'Seminars on software and literary copyrights.' },
      { title: 'IPR Clinic', date: 'Weekly', desc: 'One-on-one consultation for ongoing research projects.' },
    ],
    image: 'https://picsum.photos/seed/ipr/1200/600?blur=2'
  },
  ciil: {
    name: 'Center for Innovation & Industry Linkage',
    shortName: 'CIIL',
    color: 'from-emerald-600 to-teal-500',
    bgLight: 'bg-emerald-500/10',
    textDark: 'text-emerald-400',
    textPrimary: 'text-emerald-400',
    description: 'CIIL acts as a bridge between academia and industry, fostering collaborative research, sponsored projects, and industry-ready skill development.',
    objectives: [
      'To establish strong linkages with leading industries.',
      'To facilitate industry-sponsored projects for students.',
      'To organize joint research initiatives and consultancy.',
      'To setup industry-backed centers of excellence.',
    ],
    activities: [
      { title: 'Industry-Academia Conclave', date: 'Dec 2025', desc: 'Annual gathering of industry leaders and academic researchers.' },
      { title: 'Corporate Project Expo', date: 'May 2026', desc: 'Showcase of final year projects to industry panels.' },
      { title: 'Skill Enhancement Program', date: 'Ongoing', desc: 'Training on cutting-edge technologies demanded by industry.' },
    ],
    image: 'https://picsum.photos/seed/ciil/1200/600?blur=2'
  }
};

export default function Division() {
  const { id } = useParams<{ id: string }>();
  const [isMobile, setIsMobile] = useState(false);
  const prefersReducedMotion = useReducedMotion();

  useEffect(() => {
    const checkMobile = () => setIsMobile(window.innerWidth < 768);
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  const shouldAnimate = !prefersReducedMotion;
  
  // Type assertion since we know id will be one of the keys if routed correctly
  const data = divisionsData[id as keyof typeof divisionsData];

  if (!data) {
    return (
      <div className="min-h-[70vh] flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-2xl font-bold text-white mb-4">Division not found</h2>
          <Link to="/" className="text-gold-500 hover:text-gold-400 transition-colors inline-flex items-center gap-2">
            <ArrowLeft size={16} /> Back to Home
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="pb-24 relative overflow-hidden">
      {/* Background decorative elements */}
      <div className={`absolute top-0 left-1/2 -translate-x-1/2 w-[1000px] h-[600px] bg-gradient-to-r ${data.color} opacity-10 blur-[120px] pointer-events-none`} />

      {/* Banner */}
      <div className="relative h-[50vh] min-h-[400px] flex items-end pb-16">
        <div className="absolute inset-0">
          <img src={data.image} alt={data.name} referrerPolicy="no-referrer" className="w-full h-full object-cover" />
          <div className={`absolute inset-0 bg-gradient-to-r ${data.color} mix-blend-multiply opacity-60`} />
          <div className="absolute inset-0 bg-gradient-to-t from-navy-950 via-navy-950/80 to-transparent" />
        </div>
        
        <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full">
          <Link to="/" className="inline-flex items-center gap-2 text-slate-300 hover:text-white mb-6 transition-colors text-sm font-medium">
            <ArrowLeft size={16} /> Back to Home
          </Link>
          <motion.div
            initial={isMobile ? { opacity: 0, y: 15 } : shouldAnimate ? { opacity: 0, y: 30 } : { opacity: 1, y: 0 }}
            animate={{ opacity: 1, y: 0 }}
            transition={isMobile ? { duration: 0.4, ease: "easeOut" } : { duration: 0.8, ease: "easeOut" }}
          >
            <div className="inline-block px-4 py-1.5 rounded-full bg-white/10 backdrop-blur-md border border-white/20 text-white text-sm font-bold tracking-wider mb-6 shadow-lg">
              {data.shortName}
            </div>
            <h1 className="text-5xl md:text-7xl font-display font-bold text-white max-w-4xl leading-tight tracking-tight">
              {data.name}
            </h1>
          </motion.div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-16 relative z-10">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 lg:gap-16">
          
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-16">
            {/* About */}
            <motion.section
              initial={isMobile ? { opacity: 0, y: 12 } : shouldAnimate ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={isMobile ? { duration: 0.4, ease: "easeOut" } : { duration: 0.6 }}
            >
              <div className="flex items-center gap-3 mb-6">
                <Target className={data.textPrimary} size={32} />
                <h2 className="text-3xl md:text-4xl font-display font-bold text-white">About {data.shortName}</h2>
              </div>
              <p className="text-lg md:text-xl text-slate-300 leading-relaxed font-light">
                {data.description}
              </p>
            </motion.section>

            {/* Objectives */}
            <motion.section
              initial={isMobile ? { opacity: 0, y: 12 } : shouldAnimate ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={isMobile ? { duration: 0.4, ease: "easeOut" } : { duration: 0.6 }}
            >
              <h3 className="text-2xl md:text-3xl font-display font-bold text-white mb-8">Key Objectives</h3>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                {data.objectives.map((obj, i) => (
                  <motion.div
                    key={i}
                    initial={isMobile ? { opacity: 0, y: 12 } : shouldAnimate ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true, margin: "-50px" }}
                    transition={isMobile ? { duration: 0.4, delay: i * 0.05, ease: "easeOut" } : { delay: i * 0.1, duration: 0.5 }}
                  >
                    <Card variant="glass-dark" className="h-full p-6 hover:-translate-y-2 transition-transform duration-300">
                      <CheckCircle2 className={`${data.textPrimary} mb-4`} size={28} />
                      <p className="font-medium text-slate-200 leading-relaxed">{obj}</p>
                    </Card>
                  </motion.div>
                ))}
              </div>
            </motion.section>

            {/* Activities */}
            <motion.section
              initial={isMobile ? { opacity: 0, y: 12 } : shouldAnimate ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: "-50px" }}
              transition={isMobile ? { duration: 0.4, ease: "easeOut" } : { duration: 0.6 }}
            >
              <div className="flex items-center gap-3 mb-8">
                <Zap className={data.textPrimary} size={32} />
                <h2 className="text-3xl md:text-4xl font-display font-bold text-white">Initiatives & Activities</h2>
              </div>
              <div className="space-y-6">
                {data.activities.map((act, i) => (
                  <motion.div
                    key={i}
                    initial={isMobile ? { opacity: 0, x: -12 } : shouldAnimate ? { opacity: 0, x: -20 } : { opacity: 1, x: 0 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true, margin: "-50px" }}
                    transition={isMobile ? { duration: 0.4, delay: i * 0.05, ease: "easeOut" } : { delay: i * 0.1, duration: 0.5 }}
                  >
                    <Card variant="glass-dark" className="flex flex-col sm:flex-row gap-6 p-6 hover:-translate-y-2 transition-all duration-300 group">
                      <div className="sm:w-48 shrink-0">
                        <div className={`inline-flex items-center gap-2 px-4 py-1.5 rounded-full ${data.bgLight} ${data.textPrimary} border border-white/5 text-sm font-bold mb-2 shadow-sm`}>
                          <Calendar size={16} /> {act.date}
                        </div>
                      </div>
                      <div>
                        <h4 className="text-xl font-bold text-white mb-3 group-hover:text-gold-400 transition-colors">{act.title}</h4>
                        <p className="text-slate-400 leading-relaxed">{act.desc}</p>
                      </div>
                    </Card>
                  </motion.div>
                ))}
              </div>
            </motion.section>
          </div>

          {/* Sidebar */}
          <div className="lg:col-span-1">
            <div className="sticky top-32 space-y-8">
              {/* Quick Contact Card */}
              <motion.div
                initial={isMobile ? { opacity: 0, y: 12 } : shouldAnimate ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
                animate={{ opacity: 1, y: 0 }}
                transition={isMobile ? { duration: 0.4, delay: 0.1, ease: "easeOut" } : { duration: 0.6, delay: 0.2 }}
              >
                <Card variant="tech" className="p-8">
                  <h3 className="text-2xl font-display font-bold text-white mb-4">Connect with {data.shortName}</h3>
                  <p className="text-slate-400 text-sm mb-8 leading-relaxed">
                    Have an idea or need guidance? Reach out to the {data.shortName} coordinators.
                  </p>
                  <button className={`w-full py-4 rounded-xl bg-gradient-to-r ${data.color} text-white font-bold shadow-lg hover:shadow-xl hover:scale-[1.02] transition-all duration-300`}>
                    Contact Coordinator
                  </button>
                </Card>
              </motion.div>

              {/* Stats/Info Card */}
              <motion.div
                initial={isMobile ? { opacity: 0, y: 12 } : shouldAnimate ? { opacity: 0, y: 20 } : { opacity: 1, y: 0 }}
                animate={{ opacity: 1, y: 0 }}
                transition={isMobile ? { duration: 0.4, delay: 0.15, ease: "easeOut" } : { duration: 0.6, delay: 0.3 }}
              >
                <Card variant="glass-dark" className="p-8">
                  <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-3">
                    <Users className={data.textPrimary} size={24} /> Team Members
                  </h3>
                  <div className="space-y-6">
                    {[1, 2, 3].map((i) => (
                      <div key={i} className="flex items-center gap-4 group cursor-pointer">
                        <div className="w-12 h-12 rounded-full bg-white/10 overflow-hidden border border-white/10 group-hover:border-gold-500/50 transition-colors">
                          <img src={`https://picsum.photos/seed/user${i}${id}/100/100`} alt="User" referrerPolicy="no-referrer" className="w-full h-full object-cover group-hover:scale-110 transition-transform" />
                        </div>
                        <div>
                          <div className="font-semibold text-white text-sm group-hover:text-gold-400 transition-colors">Faculty Coordinator {i}</div>
                          <div className="text-xs text-slate-400 mt-1">Department of Engineering</div>
                        </div>
                      </div>
                    ))}
                  </div>
                  <button className="w-full mt-8 py-3 text-sm font-semibold text-white border border-white/20 rounded-xl hover:bg-white/10 transition-all duration-300">
                    View Full Team
                  </button>
                </Card>
              </motion.div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
